name: Push Triggered Action

on:
  push:
    branches:
      - main  # または master (GitHubのデフォルトブランチ名)

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # 実行環境 (Ubuntuの最新版)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # リポジトリのコードをチェックアウト

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 使用するNode.jsのバージョン (必要に応じて変更)

      - name: Install dependencies
        run: npm install  # 依存関係をインストール

      - name: Run tests (example)
        run: npm test  # テストを実行 (もしあれば)

      # 他に追加したいステップがあれば、ここに記述 (例: ビルド、デプロイなど)
      - name: Example step
        run: echo "This is an example action triggered by a push."